# Generated by Django 2.1.4 on 2019-03-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_idea_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='contenido',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
